pipeline {
    
    tools {
        maven 'Maven 3.5.4'
    }

    agent any 
    stages {
        stage('Build') { 
            steps {
                echo 'Compiling worker app'
                dir('worker'){
                sh 'mvn compile' 
                }
                
            }
        }
        stage('Test') { 
            steps {
                echo 'Running unit Test on worker app' 
                dir('worker'){
                sh 'mvn clean test' 
                }
            }
        }
        stage('Package') { 
            steps {
                echo 'Packaging worker app' 
                dir('worker'){
                sh 'mvn package -DskipTests' 
                }
            }
        }
    
    }

    post {
        always {
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
            echo 'Build pipeline fro worker is completed'
        }
    }

    
}